Repository tpgns4283/TestyPie, pull requests merged in 2024-02, with the labels that each got.

#115 Feat/castle hun
  build.gradle
  src/main/java/com/example/testypie/domain/util/CustomMultipartFile.java
  src/main/java/com/example/testypie/domain/util/S3Util.java
Labels: Refactor, feat

#119 Product 검색 기능
  build.gradle
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/dto/SearchProductResponseDTO.java
  src/main/java/com/example/testypie/domain/product/repository/ProductRepository.java
  src/main/java/com/example/testypie/domain/product/repository/SearchRepository.java
  src/main/java/com/example/testypie/domain/product/repository/SearchRepositoryImpl.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/global/config/QuerydslConfig.java
Labels: Refactor, feat

#124 #85 feat: 좋아요별 게시물 조회기능 및 프론트 및 부모 카테고리 내 모든 게시물 조회 및 프론트
  src/main/java/com/example/testypie/domain/bugreport/controller/BugReportController.java
  src/main/java/com/example/testypie/domain/category/service/CategoryService.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/repository/ProductRepository.java
  src/main/java/com/example/testypie/domain/product/repository/SearchRepositoryImpl.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
  src/main/resources/static/css/home.css
  src/main/resources/static/js/category.js
  src/main/resources/templates/home.html
  src/main/resources/templates/product.html
  src/main/resources/templates/productList.html
Labels: chore, feat

#125 #85 feat: 버그리포트 프론트 구현
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/domain/bugreport/controller/BugReportController.java
  src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
  src/main/java/com/example/testypie/domain/user/entity/User.java
  src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
  src/main/resources/templates/bugreport.html
  src/main/resources/templates/product.html
Labels: Bug, feat

#126 #85 fix: 비밀번호 수정 시 입력값이 없을 경우 빈 값이 들어오는 에러 해결
  src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
Labels: Bug

#130 #85 fix: Product Create, Update 시 공백 예외처리 추가
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/domain/bugreport/controller/BugReportController.java
  src/main/java/com/example/testypie/domain/category/service/CategoryService.java
  src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/dto/ProductUpdateRequestDTO.java
  src/main/java/com/example/testypie/domain/product/entity/Product.java
  src/main/java/com/example/testypie/domain/product/repository/ProductRepository.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/reward/dto/RewardMapper.java
  src/main/java/com/example/testypie/domain/survey/service/SurveyService.java
  src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
  src/main/java/com/example/testypie/domain/user/dto/ParticipatedProductResponseDTO.java
  src/main/java/com/example/testypie/domain/user/dto/RegisteredProductResponseDTO.java
  src/main/java/com/example/testypie/domain/user/entity/User.java
  src/main/java/com/example/testypie/global/exception/ErrorCode.java
  src/main/java/com/example/testypie/global/filter/JwtAuthorizationFilter.java
  src/main/resources/templates/addFeedback.html
  src/main/resources/templates/addProductForm.html
  src/main/resources/templates/bugreport.html
  src/main/resources/templates/home.html
  src/main/resources/templates/productList.html
  src/main/resources/templates/updateProductForm.html
Labels: Bug

#133 Feat/castle hun
  src/main/java/com/example/testypie/domain/bugreport/entity/BugReport.java
  src/main/java/com/example/testypie/domain/bugreport/service/BugReportService.java
  src/main/java/com/example/testypie/domain/category/service/CategoryService.java
  src/main/java/com/example/testypie/domain/comment/dto/response/CreateCommentResponseDTO.java
  src/main/java/com/example/testypie/domain/comment/dto/response/ReadPageCommentResponseDTO.java
  src/main/java/com/example/testypie/domain/comment/dto/response/UpdateCommentResponseDTO.java
  src/main/java/com/example/testypie/domain/comment/entity/Comment.java
  src/main/java/com/example/testypie/domain/comment/service/CommentService.java
  src/main/java/com/example/testypie/domain/commentLike/service/CommentLikeService.java
  src/main/java/com/example/testypie/domain/core/service/CommentMatcherService.java
  src/main/java/com/example/testypie/domain/feedback/entity/Feedback.java
  src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
  src/main/java/com/example/testypie/domain/product/entity/Product.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/reward/dto/request/CreateRewardRequestDTO.java
  src/main/java/com/example/testypie/domain/survey/entity/Survey.java
  src/main/java/com/example/testypie/domain/survey/service/SurveyService.java
  src/main/java/com/example/testypie/domain/util/S3Util.java
  src/main/java/com/example/testypie/global/TimeStamp.java
  src/test/java/com/example/testypie/domain/survey/SurveyCreateTest.java
Labels: Refactor, chore

#135 Feat/castle hun
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/domain/bugreport/controller/BugReportController.java
  src/main/java/com/example/testypie/domain/bugreport/entity/BugReport.java
  src/main/java/com/example/testypie/domain/bugreport/service/BugReportService.java
  src/main/java/com/example/testypie/domain/category/controller/CategoryController.java
  src/main/java/com/example/testypie/domain/category/entity/Category.java
  src/main/java/com/example/testypie/domain/category/service/CategoryService.java
  src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
  src/main/java/com/example/testypie/domain/comment/service/CommentService.java
  src/main/java/com/example/testypie/domain/commentLike/controller/commentLikeController.java
  src/main/java/com/example/testypie/domain/commentLike/entity/CommentLike.java
  src/main/java/com/example/testypie/domain/commentLike/service/CommentLikeService.java
  src/main/java/com/example/testypie/domain/core/service/CommentMatcherService.java
  src/main/java/com/example/testypie/domain/feedback/controller/FeedbackController.java
  src/main/java/com/example/testypie/domain/feedback/entity/Feedback.java
  src/main/java/com/example/testypie/domain/feedback/entity/FeedbackDetails.java
  src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/entity/Product.java
  src/main/java/com/example/testypie/domain/product/repository/SearchRepository.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/productLike/controller/ProductLikeController.java
  src/main/java/com/example/testypie/domain/productLike/entity/ProductLike.java
  src/main/java/com/example/testypie/domain/productLike/service/ProductLikeService.java
  src/main/java/com/example/testypie/domain/reward/controller/RewardController.java
  src/main/java/com/example/testypie/domain/reward/entity/Reward.java
  src/main/java/com/example/testypie/domain/reward/service/RewardService.java
  src/main/java/com/example/testypie/domain/scheduler/Scheduler.java
  src/main/java/com/example/testypie/domain/survey/controller/SurveyController.java
  src/main/java/com/example/testypie/domain/survey/entity/Option.java
  src/main/java/com/example/testypie/domain/survey/entity/Question.java
  src/main/java/com/example/testypie/domain/survey/entity/Survey.java
  src/main/java/com/example/testypie/domain/survey/service/SurveyService.java
  src/main/java/com/example/testypie/domain/user/constant/UserRole.java
  src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
  src/main/java/com/example/testypie/domain/user/entity/RefreshToken.java
  src/main/java/com/example/testypie/domain/user/entity/User.java
  src/main/java/com/example/testypie/domain/user/kakao/service/KakaoService.java
  src/main/java/com/example/testypie/domain/user/repository/UserRepository.java
  src/main/java/com/example/testypie/domain/user/service/RefreshTokenService.java
  src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
  src/main/java/com/example/testypie/domain/user/service/UserService.java
  src/main/java/com/example/testypie/domain/userrole/constant/UserRole.java
  src/main/resources/templates/product.html
  src/main/resources/templates/productList.html
  src/main/resources/templates/updateProductForm.html
  src/test/java/com/example/testypie/domain/commentLike/service/CommentLikeServiceTest.java
  src/test/java/com/example/testypie/domain/productLike/service/ProductLikeServiceTest.java
Labels: chore, Clean

#136 #85 feat: domain 전반적인 front 및 backend 예외처리
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/domain/comment/entity/Comment.java
  src/main/resources/templates/addProductForm.html
  src/main/resources/templates/home.html
  src/main/resources/templates/product.html
  src/main/resources/templates/productList.html
  src/main/resources/templates/updateProductForm.html
Labels: Bug, feat

#143 카카로 리다이렉트 spoless
  src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
  src/main/resources/templates/login.html
Labels: Bug
