Repository tpgns4283/TestyPie, pull requests merged in 2024-01, with the labels that each got.

#2 #1 feat: 도메인 별 기본 Builder 작성
  src/main/java/com/example/testypie/category/entity/Category.java
  src/main/java/com/example/testypie/comment/entity/Comment.java
  src/main/java/com/example/testypie/feedback/entity/Feedback.java
  src/main/java/com/example/testypie/product/entity/Product.java
  src/main/java/com/example/testypie/reward/entity/Reward.java
  src/main/java/com/example/testypie/reward/entity/RewardImage.java
  src/main/java/com/example/testypie/user/entity/User.java
  src/main/java/com/example/testypie/userrole/entity/UserRole.java
Labels: feat

#17 Feat/castle hun
  .gitignore
  src/main/java/com/example/testypie/TestyPieApplication.java
  src/main/resources/application.properties
Labels: Refactor

#18 #15 refactor: 오류 수정 완료
  src/main/java/com/example/testypie/TestyPieApplication.java
Labels: Refactor

#21 #20 feat: 기본적인 CI
  github/workflows/gradle.yml
Labels: Setting, feat

#25 #20 chore: 패키지 정리
  github/workflows/gradle.yml
Labels: chore

#32 Feat/castle hun
  .github/workflows/gradle.yml
  .gitignore
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: Refactor

#33 #20 factor: Dockerfile
  Dockerfile
Labels: feat

#40 Feat/castle hun
  build.gradle
  src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
  src/main/resources/application-test.properties
  src/test/java/com/example/testypie/domain/feedback/FeedbackRepositoryTest.java
Labels: chore, feat

#44 refactor: auto ddl update 로
  src/main/resources/application-test.properties
Labels: Refactor

#47 Feat/castle hun
  build.gradle
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/global/config/WebSecurityConfig.java
  src/main/java/com/example/testypie/global/filter/JwtAuthorizationFilter.java
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layouts/default.html
  src/main/resources/templates/login.html
Labels: chore, feat

#48 Feat/castle hun
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/resources/static/css/content.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/images/kakao_login_medium.png
  src/main/resources/static/images/testy_pie_logo.png
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/layouts/default.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: Refactor, chore, feat

#59 Feat/castle hun
  src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
  src/main/java/com/example/testypie/domain/product/constant/ProductConstant.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/dto/ProductCreateResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductPageResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductUpdateResponseDTO.java
  src/main/java/com/example/testypie/domain/product/entity/Product.java
  src/main/java/com/example/testypie/domain/product/repository/ProductRepository.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/productLike/Repository/ProductLikeRepository.java
  src/main/java/com/example/testypie/domain/productLike/controller/ProductLikeController.java
  src/main/java/com/example/testypie/domain/productLike/dto/ProductLikeResponseDto.java
  src/main/java/com/example/testypie/domain/productLike/entity/ProductLike.java
  src/main/java/com/example/testypie/domain/productLike/service/ProductLikeService.java
  src/main/java/com/example/testypie/domain/scheduler/Scheduler.java
  src/test/java/com/example/testypie/common/mvc/MockSpringSecurityFilter.java
  src/test/java/com/example/testypie/domain/ControllerTestSupport.java
  src/test/java/com/example/testypie/domain/feedback/FeedbackRepositoryTest.java
  src/test/java/com/example/testypie/domain/productLike/controller/ProductLikeControllerTest.java
  src/test/java/com/example/testypie/domain/productLike/service/ProductLikeServiceTest.java
Labels: Refactor, chore, feat

#66 Feat/castle hun
  src/main/java/com/example/testypie/domain/comment/constant/CommentConstant.java
  src/main/java/com/example/testypie/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/example/testypie/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/example/testypie/domain/comment/entity/Comment.java
  src/main/java/com/example/testypie/domain/comment/service/CommentService.java
  src/main/java/com/example/testypie/domain/commentLike/constant/CommentLikeConstant.java
  src/main/java/com/example/testypie/domain/commentLike/controller/commentLikeController.java
  src/main/java/com/example/testypie/domain/commentLike/dto/CommentLikeResponseDto.java
  src/main/java/com/example/testypie/domain/commentLike/entity/CommentLike.java
  src/main/java/com/example/testypie/domain/commentLike/repository/CommentLikeRepository.java
  src/main/java/com/example/testypie/domain/commentLike/service/CommentLikeService.java
  src/main/java/com/example/testypie/domain/product/constant/ProductConstant.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/productLike/Repository/ProductLikeRepository.java
  src/main/java/com/example/testypie/domain/productLike/constant/ProductLikeConstant.java
  src/main/java/com/example/testypie/domain/productLike/controller/ProductLikeController.java
  src/main/java/com/example/testypie/domain/productLike/service/ProductLikeService.java
  src/test/java/com/example/testypie/domain/commentLike/service/CommentLikeServiceTest.java
  src/test/java/com/example/testypie/domain/productLike/service/ProductLikeServiceTest.java
Labels: Refactor, chore, feat

#73 Feat/castle hun
  src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
  src/main/java/com/example/testypie/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/example/testypie/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/testypie/domain/comment/service/CommentService.java
  src/main/java/com/example/testypie/domain/core/service/CommentMatcherService.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
Labels: Refactor, chore

#75 Feat/castle hun
  src/main/java/com/example/testypie/domain/bugreport/service/BugReportService.java
  src/main/java/com/example/testypie/domain/category/controller/CategoryController.java
  src/main/java/com/example/testypie/domain/category/service/CategoryService.java
  src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
  src/main/java/com/example/testypie/domain/comment/service/CommentService.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/reward/controller/RewardController.java
  src/main/java/com/example/testypie/domain/reward/service/RewardService.java
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
  src/main/java/com/example/testypie/domain/user/service/UserService.java
Labels: chore

#78 Feature sehun survey
  src/main/java/com/example/testypie/domain/feedback/controller/FeedbackController.java
  src/main/java/com/example/testypie/domain/feedback/controller/FeedbackViewController.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackCreateResponseDTO.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackDetailsCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackDetailsReadResponseDTO.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackReadResponseDTO.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackRequestDTO.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackResponseDTO.java
  src/main/java/com/example/testypie/domain/feedback/entity/Feedback.java
  src/main/java/com/example/testypie/domain/feedback/entity/FeedbackDetails.java
  src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
  src/main/java/com/example/testypie/domain/product/entity/Product.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/reward/controller/RewardController.java
  src/main/java/com/example/testypie/domain/reward/dto/RewardMapper.java
  src/main/java/com/example/testypie/domain/reward/entity/Reward.java
  src/main/java/com/example/testypie/domain/reward/service/RewardService.java
  src/main/java/com/example/testypie/domain/survey/controller/SurveyController.java
  src/main/java/com/example/testypie/domain/survey/dto/OptionCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/OptionReadResponseDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/QuestionCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/QuestionReadResponseDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/SurveyCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/SurveyCreateResponseDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/SurveyReadResponseDTO.java
  src/main/java/com/example/testypie/domain/survey/entity/Option.java
  src/main/java/com/example/testypie/domain/survey/entity/Question.java
  src/main/java/com/example/testypie/domain/survey/entity/QuestionType.java
  src/main/java/com/example/testypie/domain/survey/entity/Survey.java
  src/main/java/com/example/testypie/domain/survey/repository/SurveyRepository.java
  src/main/java/com/example/testypie/domain/survey/service/SurveyService.java
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
  src/main/java/com/example/testypie/domain/user/service/UserService.java
  src/main/java/com/example/testypie/global/config/S3Config.java
  src/main/resources/application.properties
  src/main/resources/templates/product.html
  src/test/java/com/example/testypie/domain/feedback/FeedbackRepositoryTest.java
  src/test/java/com/example/testypie/domain/survey/SurveyCreateTest.java
Labels: Refactor, chore, feat

#79 fix: Comment Read Error 수정
  src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
  src/main/java/com/example/testypie/domain/comment/service/CommentService.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/resources/templates/product.html
Labels: Bug

#84 chore: 오타 수정 및 서식 정리
  src/main/java/com/example/testypie/domain/comment/entity/Comment.java
  src/main/java/com/example/testypie/domain/commentLike/controller/commentLikeController.java
  src/main/java/com/example/testypie/domain/product/controller/ProductController.java
  src/main/java/com/example/testypie/domain/productLike/controller/ProductLikeController.java
Labels: chore

#86 #85: 설문지 및 답변 기능 프론트 생성 완료
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/domain/feedback/controller/FeedbackController.java
  src/main/java/com/example/testypie/domain/feedback/entity/Feedback.java
  src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
  src/main/java/com/example/testypie/domain/product/entity/Product.java
  src/main/java/com/example/testypie/domain/survey/controller/SurveyController.java
  src/main/java/com/example/testypie/domain/survey/service/SurveyService.java
  src/main/resources/static/css/header.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/category.js
  src/main/resources/templates/addFeedback.html
  src/main/resources/templates/addProductForm.html
  src/main/resources/templates/addSurvey.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/layouts/default.html
  src/main/resources/templates/login.html
  src/main/resources/templates/product.html
  src/main/resources/templates/productList.html
  src/main/resources/templates/signup.html
Labels: Bug, Refactor, feat

#87 fix : Product 작성자가 Feedback 작성하는 경우 예외처리
  src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
Labels: Bug

#89 #85 fix : 로그아웃 시 refresh토큰 제거되지 않는 현상 해결
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
  src/main/resources/static/js/category.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
Labels: Bug

#91 Feat/castle hun
  src/main/java/com/example/testypie/domain/scheduler/Scheduler.java
Labels: feat

#92 #85 fix : 전체적인 CSS 수정 및 날짜 포멧팅(yyyy-DD-mm)
  src/main/java/com/example/testypie/domain/product/dto/ProductCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductPageResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/scheduler/Scheduler.java
  src/main/resources/static/css/header.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/productList.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/css/updateProfile.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/product.html
  src/main/resources/templates/productList.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProductForm.html
  src/main/resources/templates/updateProfileForm.html
Labels: Refactor, feat

#94 #85 fix: Front 예외처리
  src/main/java/com/example/testypie/domain/comment/dto/CommentResponseDTO.java
  src/main/resources/static/css/product.css
  src/main/resources/templates/login.html
  src/main/resources/templates/product.html
  src/main/resources/templates/updateProductForm.html
Labels: Refactor

#96 Feature sehun fronts
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductPageResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
  src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
  src/main/java/com/example/testypie/domain/user/controller/UserController.java
  src/main/java/com/example/testypie/domain/user/dto/ProfileRequestDTO.java
  src/main/resources/static/css/login.css
  src/main/resources/static/js/category.js
  src/main/resources/static/js/getNewToken.js
  src/main/resources/templates/addFeedback.html
  src/main/resources/templates/addProductForm.html
  src/main/resources/templates/addSurvey.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/product.html
  src/main/resources/templates/productList.html
  src/main/resources/templates/profile.html
Labels: Bug, Refactor, feat

#98 #85 fix: profile Image 수정
  src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
  src/main/java/com/example/testypie/domain/user/dto/ProfileRequestDTO.java
  src/main/java/com/example/testypie/domain/util/S3Util.java
  src/main/resources/templates/updateProfileForm.html
Labels: Bug

#99 #85 feat: ProductList에서 사용자 클릭 시 사용자 정보 Modal로 출력
  src/main/java/com/example/testypie/TestyPieApplication.java
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/example/testypie/domain/feedback/dto/FeedbackCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
  src/main/java/com/example/testypie/domain/product/dto/ProductCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductPageResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
  src/main/java/com/example/testypie/domain/product/dto/ProductUpdateRequestDTO.java
  src/main/java/com/example/testypie/domain/product/repository/ProductRepository.java
  src/main/java/com/example/testypie/domain/product/service/ProductService.java
  src/main/java/com/example/testypie/domain/reward/dto/RewardCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/scheduler/Scheduler.java
  src/main/java/com/example/testypie/domain/survey/dto/OptionCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/QuestionCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/survey/dto/SurveyCreateRequestDTO.java
  src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
  src/main/java/com/example/testypie/domain/user/entity/User.java
  src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
  src/main/resources/static/css/modal.css
  src/main/resources/static/css/productList.css
  src/main/resources/static/js/category.js
  src/main/resources/static/js/getNewToken.js
  src/main/resources/static/js/modal.js
  src/main/resources/templates/addFeedback.html
  src/main/resources/templates/addProductForm.html
  src/main/resources/templates/addSurvey.html
  src/main/resources/templates/fragments/modal.html
  src/main/resources/templates/product.html
  src/main/resources/templates/productList.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProductForm.html
  src/main/resources/templates/updateProfileForm.html
Labels: Bug, Refactor, chore, feat

#103 chore: api 수정 및 필터 설정
  src/main/java/com/example/testypie/View/controller/ViewController.java
  src/main/java/com/example/testypie/global/config/WebSecurityConfig.java
  src/main/resources/static/js/category.js
  src/main/resources/templates/addFeedback.html
  src/main/resources/templates/addProductForm.html
  src/main/resources/templates/addSurvey.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateProductForm.html
  src/main/resources/templates/updateProfileForm.html
Labels: chore

#104 chore: api 필터 수정 2
  src/main/java/com/example/testypie/global/config/WebSecurityConfig.java
Labels: chore

#105 chore: api 필터 수정 3
  src/main/java/com/example/testypie/global/config/WebSecurityConfig.java
Labels: chore

#106 chore: api 필터 수정 4
  src/main/java/com/example/testypie/global/config/WebSecurityConfig.java
Labels: chore

#107 #85 fix: 페이지 필더단에서 열음
  src/main/java/com/example/testypie/global/config/WebSecurityConfig.java
Labels: chore
